//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaSalesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public long Price_ID { get; set; }
        public int Company_ID { get; set; }
        public int PlaneType_ID { get; set; }
        public int SeatClass_ID { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
