//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaSalesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Ticket_ID { get; set; }
        public long Flight_ID { get; set; }
        public Nullable<long> PlaneSeat_ID { get; set; }
        public long Passanger_ID { get; set; }
        public Nullable<long> Price_ID { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual PlaneSeat PlaneSeat { get; set; }
        public virtual Price Price { get; set; }
    }
}
